# Random Forests for Imputing Missing Values

In [36]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer

In [37]:
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [38]:
df.isnull().sum().sort_values(ascending=False)

deck           688
age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

In [39]:
df.drop('deck', axis=1, inplace=True)

df.isnull().sum().sort_values(ascending=False)

age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
parch            0
sibsp            0
class            0
fare             0
who              0
adult_male       0
alive            0
alone            0
dtype: int64

In [40]:
imputer = SimpleImputer(strategy="most_frequent")
df[["embarked", "embark_town"]] = imputer.fit_transform(df[["embarked", "embark_town"]])

df.isnull().sum().sort_values(ascending=False)

age            177
survived         0
pclass           0
sex              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
embark_town      0
alive            0
alone            0
dtype: int64

In [41]:
column_to_encode = ['sex', 'embarked', 'who', 'class', 'embark_town', 'alive']

Label_Encoder = {}

for col in column_to_encode:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

    Label_Encoder[col] = le

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,True,2,0,False
1,1,1,0,38.0,1,0,71.2833,0,0,2,False,0,1,False
2,1,3,0,26.0,0,0,7.9250,2,2,2,False,2,1,True
3,1,1,0,35.0,1,0,53.1000,2,0,2,False,2,1,False
4,0,3,1,35.0,0,0,8.0500,2,2,1,True,2,0,True

In [42]:
# spliting data into two parts
with_missing = df[df["age"].isna()]
without_missing = df.dropna()

In [43]:
with_missing

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
5,0,3,1,NaN,0,0,8.4583,1,2,1,True,1,0,True
17,1,2,1,NaN,0,0,13.0000,2,1,1,True,2,1,True
19,1,3,0,NaN,0,0,7.2250,0,2,2,False,0,1,True
26,0,3,1,NaN,0,0,7.2250,0,2,1,True,0,0,True
28,1,3,0,NaN,0,0,7.8792,1,2,2,False,1,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,0,3,1,NaN,0,0,7.2292,0,2,1,True,0,0,True
863,0,3,0,NaN,8,2,69.5500,2,2,2,False,2,0,False
868,0,3,1,NaN,0,0,9.5000,2,2,1,True,2,0,True
878,0,3,1,NaN,0,0,7.8958,2,2,1,True,2,0,True
888,0,3,0,NaN,1,2,23.4500,2,2,2,False,2,0,False

In [44]:
without_missing

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,True,2,0,False
1,1,1,0,38.0,1,0,71.2833,0,0,2,False,0,1,False
2,1,3,0,26.0,0,0,7.9250,2,2,2,False,2,1,True
3,1,1,0,35.0,1,0,53.1000,2,0,2,False,2,1,False
4,0,3,1,35.0,0,0,8.0500,2,2,1,True,2,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,0,39.0,0,5,29.1250,1,2,2,False,1,0,False
886,0,2,1,27.0,0,0,13.0000,2,1,1,True,2,0,True
887,1,1,0,19.0,0,0,30.0000,2,0,2,False,2,1,True
889,1,1,1,26.0,0,0,30.0000,0,0,1,True,0,1,True
890,0,3,1,32.0,0,0,7.7500,1,2,1,True,1,0,True

In [ ]:
X = without_missing.drop('age', axis=1)
y = without_missing["age"]
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=42)

rfr = RandomForestRegressor(n_estimators=100, random_state=42)
rfr.fit(X_train, y_train)

rfr.predict(X_test)

array([31.02636979,  1.48813333, 29.53034413, 27.35      , 37.63669048,
        2.50123333, 26.33      , 27.91533333, 27.78503609, 29.29752381,
       39.094     , 33.67735687, 42.07466667, 26.7619855 , 38.416     ,
       26.2225    , 26.96691667, 39.38      , 31.02636979, 40.01133333,
       27.382     , 26.27835165,  3.82185   , 36.912     , 22.18566667,
       30.005     , 24.81692641, 32.37      , 12.7075    , 30.005     ,
       22.88      ,  4.53266667, 37.70153175, 31.83833333, 25.6027619 ,
       22.80777778, 39.81990873, 34.69      , 51.46      , 39.20954076,
        4.4056    , 31.00132143, 31.35      , 42.59157792, 45.9665    ,
       30.80600378, 26.50375   , 31.2775    , 41.999     , 34.98666667,
       30.71      , 35.15725304, 35.848     , 32.146875  , 26.58728571,
       32.83829293, 49.07      ,  3.48796667, 24.08444048, 33.13741337,
       41.19461905, 48.25650595, 28.99387943, 30.005     , 33.13741337,
       60.19168831,  3.3964    , 34.115     , 35.17341667, 42.829     ,
       30.005     , 33.14333333, 26.13      , 47.04166667, 26.58738095,
       28.50091667, 34.60092331, 39.20954076, 27.58933333,  5.19153333,
        4.31044444, 41.45      , 26.38      , 22.04276435, 26.7619855 ,
       29.39166667,  4.31044444, 48.25650595, 31.64553846, 23.76038889,
       40.09880556, 38.67      , 30.80600378, 19.22890476, 22.76692308,
       27.44291667, 35.21583333, 56.51333333, 31.02636979, 38.155     ,
       33.67735687, 34.87661008, 35.57148611,  6.76883571,  3.82591667,
       31.12416667, 30.18694669, 38.525     , 35.17341667, 35.53375   ,
       30.85225   , 31.00132143,  4.20646667, 35.7725    , 31.83833333,
       28.29238889, 28.436     , 12.8717    , 31.06587652, 31.06587652,
       27.968     ,  7.8700119 , 22.97366667, 30.18694669, 39.55      ,
       26.58101364, 30.005     , 30.98833333, 29.86828002, 36.91283333,
       23.25410714, 25.6027619 , 25.73654762, 30.80600378,  5.68721905,
       31.99628481, 24.81692641, 55.235     ,  4.31443333,  7.81508333,
       26.58728571, 30.80600378, 35.6885    ])

In [ ]:
y_pred = rfr.predict(with_missing.drop('age', axis=1))
with_missing["age"] = y_pred
with_missing.head()

C:\Users\M.Qasim\AppData\Local\Temp\ipykernel_22092\1816486727.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  with_missing["age"] = y_pred

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
5,0,3,1,33.338409,0,0,8.4583,1,2,1,True,1,0,True
17,1,2,1,35.642218,0,0,13.0000,2,1,1,True,2,1,True
19,1,3,0,18.357000,0,0,7.2250,0,2,2,False,0,1,True
26,0,3,1,35.571486,0,0,7.2250,0,2,1,True,0,0,True
28,1,3,0,20.651429,0,0,7.8792,1,2,2,False,1,1,True

In [80]:
complete_data = pd.concat([without_missing, with_missing], axis=0)
print("shape of complete data frame:", complete_data.shape)
complete_data.head()

shape of complete data frame: (891, 14)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,True,2,0,False
1,1,1,0,38.0,1,0,71.2833,0,0,2,False,0,1,False
2,1,3,0,26.0,0,0,7.9250,2,2,2,False,2,1,True
3,1,1,0,35.0,1,0,53.1000,2,0,2,False,2,1,False
4,0,3,1,35.0,0,0,8.0500,2,2,1,True,2,0,True

In [82]:
for col in column_to_encode:
    le = Label_Encoder[col]
    complete_data[col] = le.inverse_transform(df[col])

complete_data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [83]:
complete_data.isnull().sum().sort_values(ascending=False)

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64